# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ment_form', '0004_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='info',
            field=models.IntegerField(default=0),
        ),
    ]
